# Site settings
title: Portfolio
description: My Portfolio
# baseurl: "/portfolio" # the subpath of your site
# url: "localhost:3000" # the base hostname & protocol for your site 

# User settings
username: Roi Meshulam
user_description: Computer science and mathematics student, passionate about software development and about getting to know and understand new technologies. I'm a self learner and I want to learn as much as I can. I have experience with Java , Python , C/C++, OOP ,HTML,CSS , JavaSctipt, Data Structures , Algorithms and Networking. 
user_title: Software Developer
email: rohimesh21@gmail.com
github_username:  RoiMeshulam


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
